In [1]:
pip install html5lib

Requirement already satisfied: html5lib in c:\users\ganger\anaconda3\lib\site-packages (1.1)
Requirement already satisfied: webencodings in c:\users\ganger\anaconda3\lib\site-packages (from html5lib) (0.5.1)
Requirement already satisfied: six>=1.9 in c:\users\ganger\anaconda3\lib\site-packages (from html5lib) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [39]:
import pandas as pd
import numpy as np
import html
import matplotlib.pyplot as plt

In [27]:
html = 'http://www.espn.com/nba/history/awards/_/id/33'
csv = 'my_file.csv'
datat = pd.read_html(html)
df = pd.DataFrame(datat[0])
df

,0,1,2,3,4,5,6,7,8,9
0,MVP,MVP,MVP,MVP,MVP,MVP,MVP,MVP,MVP,MVP
1,YEAR,PLAYER,POS,TEAM,FG%,PPG,RPG,APG,BLKPG,NaN
2,2022,Nikola Jokic,C,Denver Nuggets,.583,27.1,13.8,7.9,0.9,NaN
3,2021,Nikola Jokic,C,Denver Nuggets,.566,26.4,10.8,8.3,0.7,NaN
4,2020,Giannis Antetokounmpo,F,Milwaukee Bucks,.553,29.5,13.6,5.6,1.0,NaN
...,...,...,...,...,...,...,...,...,...,...
64,1960,Wilt Chamberlain,NaN,Philadelphia Warriors,No stats available.,No stats available.,No stats available.,No stats available.,No stats available.,NaN
65,1959,Bob Pettit,NaN,St. Louis Hawks,No stats available.,No stats available.,No stats available.,No stats available.,No stats available.,NaN
66,1958,Bill Russell,NaN,Boston Celtics,No stats available.,No stats available.,No stats available.,No stats available.,No stats available.,NaN
67,1957,Bob Cousy,NaN,Boston Celtics,No stats available.,No stats available.,No stats available.,No stats available.,No stats available.,NaN
68,1956,Bob Pettit,NaN,St. Louis Hawks,No stats available.,No stats available.,No stats available.,No stats available.,No stats available.,NaN

In [28]:
type(df)

pandas.core.frame.DataFrame

In [35]:
new_df = df.iloc[1:26,0:9]

In [57]:
new_df.rename(columns=df.iloc[1], inplace = True)

In [62]:
new_df

1,YEAR,PLAYER,POS,TEAM,FG%,PPG,RPG,APG,BLKPG
1,YEAR,PLAYER,POS,TEAM,FG%,PPG,RPG,APG,BLKPG
2,2022,Nikola Jokic,C,Denver Nuggets,.583,27.1,13.8,7.9,0.9
3,2021,Nikola Jokic,C,Denver Nuggets,.566,26.4,10.8,8.3,0.7
4,2020,Giannis Antetokounmpo,F,Milwaukee Bucks,.553,29.5,13.6,5.6,1.0
5,2019,Giannis Antetokounmpo,F,Milwaukee Bucks,.578,27.7,12.5,5.9,1.5
6,2018,James Harden,G,Houston Rockets,.449,30.4,5.4,8.8,0.7
7,2017,Russell Westbrook,G,Oklahoma City Thunder,.425,31.6,10.7,10.4,0.4
8,2016,Stephen Curry,G,Golden State Warriors,.504,30.1,5.4,6.7,0.2
9,2015,Stephen Curry,G,Golden State Warriors,.487,23.8,4.3,7.7,0.2
10,2014,Kevin Durant,F,Oklahoma City Thunder,.503,32.0,7.4,5.5,0.7
11,2013,LeBron James,F,Miami Heat,.565,26.8,8.0,7.3,0.9
12,2012,LeBron James,SF,Miami Heat,.531,27.1,7.9,6.2,0.8
13,2011,Derrick Rose,PG,Chicago Bulls,.445,25.0,4.1,7.7,0.6
14,2010,LeBron James,SF,Cleveland Cavaliers,.503,29.7,7.3,8.6,1.0
15,2009,LeBron James,SF,Cleveland Cavaliers,.489,28.4,7.6,7.2,1.1
16,2008,Kobe Bryant,SF,Los Angeles Lakers,.459,28.3,6.3,5.4,0.5
17,2007,Dirk Nowitzki,F,Dallas Mavericks,.502,24.6,8.9,3.4,0.8
18,2006,Steve Nash,PG,Phoenix Suns,.512,18.8,4.2,10.5,0.2
19,2005,Steve Nash,PG,Phoenix Suns,.502,15.5,3.3,11.5,0.1
20,2004,Kevin Garnett,PF,Minnesota Timberwolves,.499,24.2,13.9,5.0,2.2
21,2003,Tim Duncan,C,San Antonio Spurs,.513,23.3,12.9,3.9,2.9
22,2002,Tim Duncan,C,San Antonio Spurs,.508,25.5,12.7,3.7,2.5
23,2001,Allen Iverson,SG,Philadelphia 76ers,.420,31.1,3.8,4.6,0.3
24,2000,Shaquille O'Neal,C,Los Angeles Lakers,.574,29.7,13.6,3.8,3.0
25,1999,Karl Malone,PF,Utah Jazz,.493,23.8,9.4,4.1,0.6

In [48]:
positions = new_df.rename(columns=df.iloc[0]).loc[1,:]

In [53]:
new_df.columns = new_df.iloc[0]

1      FG%
2     .583
3     .566
4     .553
5     .578
6     .449
7     .425
8     .504
9     .487
10    .503
11    .565
12    .531
13    .445
14    .503
15    .489
16    .459
17    .502
18    .512
19    .502
20    .499
21    .513
22    .508
23    .420
24    .574
25    .493
Name: FG%, dtype: object